name: Build Motorola One 5G Ace (LineageOS 23.2 A16) (Kernel 4.19)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "motorola_one_5g_ace"
  DEVICE_CODENAME : "kiev"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/LineageOS/android_kernel_motorola_sm8250.git"
  KERNEL_BRANCH : "lineage-23.2"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/lito-perf_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""
  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "xxksu"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""
  NEED_DTBO : true
  NEED_SAFE_DTBO : true

  ROM_TEXT : "lineageos_23.2_4.19"
  PYTHON_VERSION: "3"

  PACK_METHOD: "AnyKernel3"
  PACK_KMODULES: "false"

  KERNELSU_METHOD: "shell"

  PATCHES_SOURCE: "cyberc3dr/nGKI_Kernel_Build"
  PATCHES_BRANCH: "xxksu-support"

  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "false"
  DROIDSPACES_ENABLE: "false"
  NOMOUNT_ENABLE: "false"

  HOOK_METHOD: "syscall"
  KERNEL_PATCH: "false"

  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: ""

  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"

  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"

  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""

  FREE_MORE_SPACE: "true"

jobs:
  build-kernel:
    name: Motorola One 5G Ace (LineageOS 23.2 A16) (Kernel 4.19)
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v6

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get necessary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          # Nothing special for kiev

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
